application: apptools-powered
version: beta
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "0m"


#### ===== Files to Skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$


#### ===== Libraries
libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: webob
  version: "latest"
- name: setuptools
  version: "latest"


#### ===== Builtin SDK Includes
#builtins:
#- appstats: on
#- deferred: on
#- mapreduce: on
#- remote_api: on
#- admin_redirect: on
#- datastore_admin: on


#### ===== Incoming Services
#inbound_services:
#- mail
#- warmup
#- xmpp_message
#- xmpp_presence
#- xmpp_subscribe
#- channel_presence


#### ===== Force precompilation
derived_file_type:
- python_precompiled


#### ===== Custom Admin Pages
admin_console:
  pages:
  - name: Developer's Console
    url: /_app/dev
  - name: Management Console
    url: /_app/manage
  - name: Map/Reduce
    url: /_ah/mapreduce/
  - name: Pipelines
    url: /_ah/pipeline/status
  - name: AppStats
    url: /_ah/stats


#### ===== Error Handlers
error_handlers:
  - file: errors/default_error.html
  - error_code: over_quota
    file: errors/over_quota.html
  - error_code: dos_api_denial
    file: errors/dos_denial.html
  - error_code: timeout
    file: errors/timeout.html


#### ===== Site Handlers
handlers:


###### Library/system mappings

# AppTools: development + debugging console
- url: /_ah/apptools.*
  script: lib.apptools.gateway
  login: admin
  auth_fail_action: unauthorized

- url: /_app/manifest.*
  script: lib.apptools.gateway
  login: optional
  secure: optional
  auth_fail_action: unauthorized

- url: /_app/sitemap.*
  script: lib.apptools.gateway
  login: optional
  secure: optional
  auth_fail_action: unauthorized

# AppTrace: memory profiling
- url: /_ah/apptrace.*
  script: lib.dist.apptrace.overview.main
  login: admin
  auth_fail_action: unauthorized

# AppStats: RPC profiling
- url: /_ah/appstats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin
  secure: always
  auth_fail_action: unauthorized

# AppEngine Pipelines
- url: /_ah/pipeline.*
  script: main.pipelines

# Instance Warmup Hook
- url: /_ah/warmup.*
  script: main.warmup
  login: admin
  auth_fail_action: unauthorized

# Backend Start Hook
- url: /_ah/start.*
  script: main.backend
  login: admin
  auth_fail_action: unauthorized


###### Asset Handlers

# Images (Static)
- url: /assets/img/static
  static_dir: assets/img/static
  expiration: "364d"

# Style (Static)
- url: /assets/style/static
  static_dir: assets/style/static
  mime_type: text/css
  expiration: "364d"

# Scripts (Static)
- url: /assets/js/static
  static_dir: assets/js/static
  mime_type: text/javascript
  expiration: "364d"

# Generic (Static)
- url: /assets/ext/static
  static_dir: assets/ext/static
  expiration: "364d"

# Dynamic Assets
- url: /assets/.*
  script: main.DynamicAsset


###### Static Handlers

# Root-level files
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "0m"

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(.*)
  expiration: "0m"

# Static HTML5 Appcache Manifest
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/appcache/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

# Chrome Extensions
- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)


###### Static directory
- url: /static
  static_dir: static


###### Everything else goes to AppTools
- url: /.*
  login: optional
  secure: optional
  script: lib.apptools.dispatch.gateway
  auth_fail_action: redirect
