application: apptools-powered
version: beta
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "365d"


#### ===== Files to Skip
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$


#### ===== Libraries
libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"


#### ===== Builtin SDK Includes
builtins:
- appstats: on
- deferred: on
- remote_api: on
- admin_redirect: on
- datastore_admin: on


#### ===== Incoming Services
#inbound_services:
#- mail
#- warmup
#- xmpp_message
#- xmpp_presence
#- xmpp_subscribe
#- channel_presence


#### ===== Force precompilation
derived_file_type:
- python_precompiled


#### ===== Custom Admin Pages
admin_console:
  pages:
  - name: Developer's Console
    url: /_app/dev
  - name: Management Console
    url: /_app/manage
  - name: Map/Reduce
    url: /_ah/mapreduce/
  - name: Pipelines
    url: /_ah/pipeline/status
  - name: AppStats
    url: /_ah/stats


#### ===== Error Handlers
error_handlers:
  - file: errors/default_error.html
  - error_code: over_quota
    file: errors/over_quota.html
  - error_code: dos_api_denial
    file: errors/dos_denial.html
  - error_code: timeout
    file: errors/timeout.html


#### ===== Site Handlers
handlers:

###### Asset Handlers

# Images (Static)
- url: /assets/img/static
  static_dir: assets/img/static

# Images (Dynamic)
- url: /assets/img/.*
  script: assets.dynamic.DynamicAsset

# Style (Static)
- url: /assets/style/static
  static_dir: assets/style/static
  mime_type: text/css
  expiration: "365d"

# Style (Dynamic)
- url: /assets/style/.*
  script: assets.dynamic.DynamicAsset

# Scripts (Static)
- url: /assets/js/static
  static_dir: assets/js/static
  mime_type: text/javascript
  expiration: "365d"  
  
# Scripts (Dynamic)
- url: /assets/js/.*
  script: assets.dynamic.DynamicAsset

# Generic (Static)
- url: /assets/ext/static
  static_dir: assets/ext/static

# Generic (Dynamic)
- url: /assets/ext/.*
  script: assets.dynamic.DynamicAsset
  
# Library/system mappings
- url: /_ah/apptrace.*
  script: lib.dist.apptrace.overview.main
  login: admin
  auth_fail_action: unauthorized
    
- url: /_ah/warmup.*
  script: main.warmup
  login: admin
  auth_fail_action: unauthorized

- url: /_ah/start
  script: main.warmup
  login: admin
  auth_fail_action: unauthorized


###### Static Handlers

# Root-level files
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "0m"
  
- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(.*)
  expiration: "0m"
 
# HTML5 Appcache Manifest
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/appcache/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

# Chrome Extensions
- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  static_files: static/\1
  upload: static/(.*\.crx)

###### Static directory
- url: /static
  static_dir: static

###### Providence/Clarity Mappings
- url: /_pc/manage/.*
  script: momentum.platform.gateway.ManagementConsole
  login: admin
  auth_fail_action: redirect

###### API Requests to the Gateway
- url: /_api/rpc.*
  script: main.services
  login: optional
  auth_fail_action: unauthorized

###### Google Verification
- url: /googlee6f418a79df92b65.html
  static_files: static/google_verify.html
  upload: static/google_verify.html
  
###### Send to Tipfy
- url: /.*
  login: admin
  secure: optional
  script: main.main
  auth_fail_action: redirect